### ISSUE TITLE
Examples of Joint Pruning, Quantization and Distillation

### ISSUE THREAD

**Issue by g12bftd** [JulesBelveze/bert-squeeze#49]
Hey, 
Thank you for making this repo public.

Do you have any example scripts that combine pruning, quantization and distillation (ideally for BERT-Base models)?

**Comment by JulesBelveze** [comment]
Hey @g12bftd thanks for showing interest!

I am actually cooking up some tutorial notebooks right now! I will add one that combines pruning, quantization and distillation for you 🤓 I'll ping you once ready!

**Comment by g12bftd** [comment]
Hey @JulesBelveze, thank you so much! If you could show an example where teacher = Bert-large-uncased and student= bert-base-uncased on any of the glue tasks, it would be fantastic!

**Comment by g12bftd** [comment]
Hey @JulesBelveze, thank you for getting back so quickly. I am trying to run the notebook in Google Colab. Some of the required packages cannot be installed with poetry. Any advice?

**Comment by JulesBelveze** [comment]
@g12bftd Are you trying to install it from the `docs/tutorials` branch?

**Comment by g12bftd** [comment]
Hey @JulesBelveze, I've attached my full notebook in a zip file. You should be able to see the exact lines of code I execute as well as the corresponding error messages.
[KD and Quant BERT.ipynb.zip](https://github.com/JulesBelveze/bert-squeeze/files/11720974/KD.and.Quant.BERT.ipynb.zip)

**Comment by JulesBelveze** [comment]
Sweet thanks, can you try to replace:
```
!git clone https://github.com/JulesBelveze/bert-squeeze.git
```
by:
```
!git clone -b docs/tutorials https://github.com/JulesBelveze/bert-squeeze.git
```

**Comment by JulesBelveze** [comment]
@g12bftd those don't seem related to `bert-squeeze` but more to hardware stuff 😅 
Could you directly share with me your Colab's url??

**Comment by g12bftd** [comment]
@JulesBelveze yeah I figured. Here is the link: https://colab.research.google.com/drive/1zKcerP-LhcHSv2uM5lnou1yECptIjrvb?usp=sharing. Thanks again for your help!

**Comment by JulesBelveze** [comment]
Jeez I hate notebooks 🤣 
I am fighting with the numpy installation.. There might be a compatibility issue with Python 3.10 and this version of numpy 🤔

**Comment by JulesBelveze** [comment]
@g12bftd can you try to install the latest version and check with it?
